version: '3.7'
services:

  jobsite:
    image: nginx:alpine
    container_name: jobsite-test
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
      - "8444:443"
    networks:
      - webserver
    volumes:
      - type: bind
        source: ./www/jobsite
        target: /usr/share/nginx/html
      - type: bind
        source: ./etc/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: ./etc/nginx/conf.d
        target: /etc/nginx/conf.d

networks:
  webserver:
    driver: bridge
